### ISSUE TITLE
Issues with RabbitMQ.Client 3.5.0

### ISSUE THREAD

**Issue by farzadpanahi** [haf/NLog.RabbitMQ#22]
Looks like the current NLog.RabbitMQ target needs some modifications to support RabbitMQ.Client 3.5.0. 

I am getting the following exception on init:
```
NLog.NLogConfigurationException: Error during initialization of RabbitMQ Target[RabbitMQTarget_BLAH_wrapped] ---> System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Could not load type 'RabbitMQ.Client.Events.ConnectionShutdownEventHandler' from assembly 'RabbitMQ.Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=89e7d7c5feba84ce'..
Result StackTrace:	
at NLog.Targets.RabbitMQ.<StartConnection>m__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
 --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at NLog.Targets.RabbitMQ.StartConnection()
   at NLog.Targets.RabbitMQ.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)
   at NLog.Targets.Target.NLog.Internal.ISupportsInitialize.Initialize(LoggingConfiguration configuration)
   at NLog.Config.LoggingConfiguration.InitializeAll()
 --- End of inner exception stack trace ---
    at NLog.Config.LoggingConfiguration.InitializeAll()
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetLogger(String name)
```

Looks like that `RabbitMQ.Client.Events.ConnectionShutdownEventHandler` is removed in the new version.

Also on NLog shutdown when I call `LogManager.Shutdown()` I get the following exception:
```
Method not found: 'Void RabbitMQ.Client.ShutdownEventArgs..ctor(RabbitMQ.Client.ShutdownInitiator, UInt16, System.String)'.
```

**Comment by haf** [comment]
This has been fixed through a PR.
